import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {Box,Container,Flex,Text} from "@chakra-ui/react"
import { motion } from 'framer-motion'
import Navbar from '@/components/TopNavbar'
import TopContainer from "@/components/TopContainer"
import BottomContainer from '@/components/BottomContainer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>NIKE SHOE DESIGN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favpng_nike-air-max-97-sports-shoes-nike-air-max-270-swoosh 1.png" />
      </Head>
    

    <Box display={'flex'} justifyContent={'center'} alignItems={'center'} padding={5}>

      <Box as={motion.div} width={'80%'} margin={'auto'} height={550} marginTop={'50px'} padding={1} style={{background:'url("/BCK.png")',backgroundRepeat:'no-repeat',backgroundSize:'cover'}} initial={{opacity:0,rotateX:0}} animate={{opacity:1,scale:1,rotateX:360}} transition={{duration:1.5,ease:'linear'}}>
    <Navbar/>
    <TopContainer/><br/><br/>
    <BottomContainer/>
      </Box>

    </Box>
     
          
    </>
  )
}
